services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - gold_chicken_net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - gold_chicken_net

  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gold_chicken_net

networks:
  gold_chicken_net:
    driver: bridge