services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8080:8080" # In production, only this port can be accessed from outside
    environment:
      - API_HOST="backend"
      - API_PORT="8081"
    depends_on:
      - backend
    networks:
      - gold_chicken_net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["python3", "./backend/startup.py"]
    ports:
      - "8081:8081"
    environment:
      - DEFAULT_ADMIN_USER="admin"
      - DEFAULT_ADMIN_PASSWORD="admin" # Change this in production
      - API_HOST="0.0.0.0"
      - API_PORT="8081"
      - REDIS_HOST="db"
      - REDIS_PORT="6379"
    depends_on:
      - db
    networks:
      - gold_chicken_net

  opt_server:
    build:
      context: .
      dockerfile: ./opt_server/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./strategies:/app/strategies
    depends_on:
      - db
    networks:
      - gold_chicken_net

  trader:
    build:
      context: .
      dockerfile: ./trader/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./strategies:/app/strategies
    depends_on:
      - db
    networks:
      - gold_chicken_net

  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gold_chicken_net

networks:
  gold_chicken_net:
    driver: bridge